name: Publish nugets

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NUGET_FEED: https://nuget.pkg.github.com/Itenium-Forge/index.json

jobs:
  publish-nugets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§° Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ“¦ Restore dependencies
        run: dotnet restore

      - name: ğŸ·ï¸ VERSION from tag
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}"

      - name: ğŸ› ï¸ Build
        run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}

      - name: ğŸ“¦ Create NuGet packages
        run: dotnet pack --no-build --configuration Release /p:Version=${VERSION} --output ./nupkgs

      - name: ğŸ“¤ Publish NuGet packages
        run: |
          for package in ./nupkgs/*.nupkg; do
            echo "Publishing $package"
            dotnet nuget push "$package" --source $NUGET_FEED --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done
