name: Publish nugets

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-nugets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§° Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ“¦ Restore dependencies
        run: dotnet restore

      - name: Set VERSION variable from tag
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}"

      - name: ğŸ› ï¸ Build
        run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}

      - name: ğŸ“¦ Create NuGet package
        run: dotnet pack --no-build --configuration Release /p:Version=${VERSION} --output .

      # - name: ğŸ“¤ Publish nuget
      #   # run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      #   #
      #   run: |
      #     dotnet nuget push ./out/*.nupkg --source github --skip-duplicate

      - name: ğŸ“¤ Publish nuget
        run: dotnet nuget push Itenium.Forge.Settings.${VERSION}.nupkg --source https://nuget.pkg.github.com/Itenium-Forge/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      # - name: ğŸ“¤ Publish nuget
      #   run: |
      #     dotnet nuget add source --username laoujin --password ${{ secrets.PackagePublish }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Itenium-Forge/index.json"
      #     dotnet nuget push Itenium.Forge.Settings.${VERSION}.nupkg --source github --skip-duplicate
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
